license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Groupix05/DynamicTrees-Super-Block-World/issues"

[[mods]]
modId="dt_super_block_world"
version="${file.jarVersion}"
displayName="Dynamic Trees for Super Block World"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-super-block-world"
logoFile="logo.png"
credits=""
authors="WenXin2"
description='''
Adds Dynamic Trees compatibility for Super Block World.
'''

[[dependencies.dt_super_block_world]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_super_block_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_super_block_world]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dt_super_block_world]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[1.2.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dt_super_block_world]]
    modId="super_block_world"
    mandatory=true
    versionRange="[0.0.8-1.20,)"
    ordering="AFTER"
    side="BOTH"